### ISSUE TITLE
Doctype Declaration

### ISSUE THREAD

**Issue by zharry** [SirTechnical/HwClicker#4]
before the start html tag add

<!DOCTYPE html>

so lines one and two look like
<!DOCTYPE html>
<html>

**Comment by SirTechnical** [comment]
When I declare a doctype, it messes everything up :\

**Comment by zharry** [comment]
Looks fine to me, what messes up?

**Comment by SirTechnical** [comment]
The styles. And I just found out why. More things to fix for 1.5!

**Comment by ZTian3** [comment]
what was the cause?

**Comment by SirTechnical** [comment]
Very stupid things. I solved this problem!

**Comment by zharry** [comment]
what was it?
